elasticsearch:
  build: elasticsearch/
  volumes:
    - /root/es/:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: logstash agent -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
  links:
    - elasticsearch
collectd:
  hostname: collectd01
  domainname: collectd01.com
  image: yaronr/collectd
  ports:
   - "25826:25826/udp"
  volumes:
    - ./etc/collectd/collectd.conf:/etc/collectd/collectd.conf.bak
    - ./collectd/collectd.conf:/etc/collectd/collectd.conf
  links:
   - logstash
kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
