# Not built
elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"

logstash:
  build: logstash/
  ports:
    - "5000:5000"
  links:
    - elasticsearch

collectd:
  hostname: collectd01
  domainname: collectd01.com
  build: collectd/
  ports:
   - "25826:25826/udp"
  links:
   - logstash

kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
